enableImmutableInstalls: true

logFilters:
  - code: YN0013
    level: discard

nmHoistingLimits: none

nmSelfReferences: false
nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@xgovformbuilder/model@*":
    dependencies:
      joi: 17.13.3
  "@xgovformbuilder/queue-model@*":
    dependencies:
      joi: 17.13.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
