# This file only contains base configuration needed for CI build and test
# For local development environment, please see docker-compose.dev.yml
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:stable
    environment:
      - SERVICES=s3,sqs
      - PERSISTENCE=/var/lib/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - ./docker-localstack:/etc/localstack/init/ready.d
      - ./localstack-data:/var/lib/localstack
