FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --ignore-scripts

COPY src/ ./src/
COPY tsconfig.json ./
RUN adduser -D nodeuser && chown -R nodeuser:nodeuser /app
USER nodeuser

EXPOSE 8081

CMD ["npm", "run", "start"]