# ----------------------------
# Stage 1
# Base image contains the node version and app user creation
# It also configures the non-root user that will be given permission to copied files/folders in every subsequent stages
FROM node:20-alpine AS base-image
RUN mkdir -p /usr/src/app/digital-form-builder-adapter && \
    addgroup -g 1001 appuser && \
    adduser -S -u 1001 -G appuser appuser && \
    find /usr/src/app/digital-form-builder-adapter -type d -exec chmod 755 {} \; && \
    apk update && \
    apk add --no-cache bash git


# ----------------------------
# Stage 2
# Cache layer contains yarn configurations
# It will re-run only if there is a yarn configuration change
FROM base-image AS yarn-build
WORKDIR /usr/src/app/digital-form-builder-adapter
RUN mkdir -p .yarn/cache && chmod 777 .yarn/cache
COPY --chown=root:root --chmod=644 ../.yarn .yarn
COPY --chown=root:root --chmod=644 ../.yarnrc.yml .yarnrc.yml
RUN chmod 755 .yarn/releases/yarn-*.cjs



# ----------------------------
# Stage 3
# Cache layer contains digital-form-builder-adapter configurations
# It will re-run only if there is a configuration change
FROM yarn-build AS digital-form-builder-adapter-pre-build
WORKDIR /usr/src/app/digital-form-builder-adapter
COPY --chown=root:root --chmod=644 .git ./.git
COPY --chown=root:root --chmod=644 .gitmodules ./.gitmodules
RUN git submodule update --init --recursive
COPY --chown=root:root --chmod=644 ../package.json package.json
COPY --chown=root:root --chmod=644 ../tsconfig.json tsconfig.json
COPY --chown=root:root --chmod=644 ../update-package.js update-package.js
COPY --chown=root:root --chmod=644 ../yarn.lock yarn.lock
COPY --chown=root:root --chmod=644 ../designer/package.json ./designer/package.json
COPY --chown=root:root --chmod=644 ../runner/package.json ./runner/package.json
COPY --chown=root:root --chmod=644 ../model/package.json ./model/package.json


# ----------------------------
# Stage 4
# Cache layer contains digital-form-builder-adapter dependencies
# It will re-run only if there is a dependency change
FROM digital-form-builder-adapter-pre-build AS digital-form-builder-adapter-install
WORKDIR /usr/src/app/digital-form-builder-adapter
RUN chmod 755 update-package.js
RUN --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-install  \
    node update-package.js && yarn setup && yarn install


# ----------------------------
# Stage 5
# Cache layer contains XGovFormBuilder with yarn build with dependencies
# It will re-run only if there is a XGovFormBuilder change
FROM digital-form-builder-adapter-install AS digital-form-builder-build
WORKDIR /usr/src/app/digital-form-builder-adapter
WORKDIR /usr/src/app/digital-form-builder-adapter/digital-form-builder
RUN --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-build \
    --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-install  \
    yarn && yarn model build && yarn queue-model build


# ----------------------------
# Stage 6
# Cache layer contains model changes
# It will re-run only if there is a model change
FROM digital-form-builder-build AS digital-form-builder-adapter-model-pre-build
WORKDIR /usr/src/app/digital-form-builder-adapter
COPY --chown=root:root --chmod=644 ../model ./model


# ----------------------------
# Stage 7
# Cache layer contains model build
# It will re-run only if there is a model change and a build change
FROM digital-form-builder-adapter-model-pre-build AS digital-form-builder-adapter-model-build
WORKDIR /usr/src/app/digital-form-builder-adapter
RUN --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-build  \
    --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-install  \
    --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-model-build
RUN yarn model build


# ----------------------------
# Stage 8
# Cache layer contains designer changes
# It will re-run only if there is a designer change
FROM digital-form-builder-adapter-model-build AS digital-form-builder-adapter-designer-pre-build
WORKDIR /usr/src/app/digital-form-builder-adapter
COPY --chown=root:root --chmod=644 ../designer ./designer


# ----------------------------
# Stage 9
# Cache layer contains designer build
# It will re-run only if there is a designer change and a build change
FROM digital-form-builder-adapter-designer-pre-build AS digital-form-builder-adapter-designer-build
WORKDIR /usr/src/app/digital-form-builder-adapter
RUN --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-build  \
    --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-install  \
    --mount=type=cache,target=.yarn/cache,uid=1001,mode=0777,id=digital-form-builder-adapter-model-build  \
    yarn designer build

RUN chown -R appuser:appuser /usr/src/app/digital-form-builder-adapter/designer
USER appuser
CMD ["yarn", "designer", "dev"]








