name: CI Build and Dockerize (build outside Docker)

on:
  push:

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: "funding-service-design-form-runner-adapter"
  IMAGE_NAME_DESIGNER: "funding-service-design-form-designer-adapter"
  IMAGE_REPO_PATH: "ghcr.io/${{github.repository_owner}}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: corepack enable

      - uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Clean legacy Yarn env (just in case)
        run: unset YARN_CACHE_DIR || true

      - name: Remove unwanted yarn.lock
        run: rm -f digital-form-builder/yarn.lock

      - name: Install deps
        env:
          YARN_CACHE_FOLDER: .yarn/cache
        run: yarn install --immutable --inline-builds

      - name: Build model
        run: yarn digital-form-builder/model build && yarn model build

      - name: Build runner
        run: yarn runner build

      - name: Build designer
        run: yarn designer build

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata Runner
        id: metadata_runner
        uses: docker/metadata-action@v4
        with:
          images: ${{env.IMAGE_REPO_PATH}}/${{env.IMAGE_NAME}}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{env.VERSION}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest
            type=ref,event=branch

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push runner
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata_runner.outputs.tags}}
          labels: ${{ steps.metadata_runner.outputs.labels }}
          push: true
          file: ./runner/runner.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            LAST_TAG='${{env.VERSION}}'
            LAST_COMMIT='${{ github.sha }}'

      - name: Docker metadata Designer
        id: metadata_designer
        uses: docker/metadata-action@v4
        with:
          images: ${{env.IMAGE_REPO_PATH}}/${{env.IMAGE_NAME_DESIGNER}}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{env.VERSION}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest
            type=ref,event=branch

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push designer
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata_designer.outputs.tags}}
          labels: ${{ steps.metadata_designer.outputs.labels }}
          push: true
          file: ./designer/designer.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            LAST_TAG='${{env.VERSION}}'
            LAST_COMMIT='${{ github.sha }}'

      - name: Injecting image into docker compose e2e
        run: |
          yq -i '.services.designer.image = "ghcr.io/communitiesuk/funding-service-design-form-designer-adapter:sha-${{ github.sha }}"'  docker-compose.e2e.yml
          yq -i '.services.runner.image = "ghcr.io/communitiesuk/funding-service-design-form-runner-adapter:sha-${{ github.sha }}"'  docker-compose.e2e.yml

      - name: Start containers
        run: docker compose -f docker-compose.e2e.yml up -d

      - name: Add localstack to /etc/hosts
        run: |
          echo "127.0.0.1 localhost localstack host.docker.internal" | sudo tee -a /etc/hosts
          cat /etc/hosts

      - name: Create S3 bucket
        run: docker exec localstack /bin/sh -c "awslocal s3api create-bucket --bucket fsd-bucket --create-bucket-configuration LocationConstraint=eu-west-2 --region eu-west-2"

      - name: Create S3 cors
        run: |
          docker exec localstack /bin/sh -c "awslocal s3api put-bucket-cors --bucket fsd-bucket --cors-configuration '{\"CORSRules\": [{\"AllowedOrigins\": [\"*\"],\"AllowedMethods\": [\"GET\", \"PUT\", \"POST\", \"DELETE\", \"HEAD\"],\"AllowedHeaders\": [\"*\"]}]}'"

      - name: Run e2e tests
        id: e2e
        run: yarn e2e-test cypress run
        continue-on-error: true

      - name: Upload E2E Test Report Application
        if: success() || failure()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: e2e-test-report-application
          path: ./e2e-test/cypress/screenshots
          retention-days: 1

      - name: Check for errors & exit the job
        run: |
          if [ "${{ steps.e2e.outcome }}" == "failure" ]; then
            echo "Test failures please fix before deploying the service"
            exit 1
          fi
