name: Increment version

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install

      - name: Print package.json version (before)
        run: |
          echo "package.json version (before): $(jq -r .version package.json)"

      - name: Run semantics release
        run: |
          npm version patch --no-git-tag-version

      - name: Print package.json version (after)
        run: |
          echo "package.json version (after): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}
